/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspacesRouteImport } from './routes/workspaces'
import { Route as SchedulerRouteImport } from './routes/scheduler'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'
import { Route as ApiYoutubeSyncRouteImport } from './routes/api/youtube/sync'
import { Route as ApiYoutubeMetricsRouteImport } from './routes/api/youtube/metrics'
import { Route as ApiTeamLoginRouteImport } from './routes/api/team/login'
import { Route as ApiAiGenerateRouteImport } from './routes/api/ai/generate'
import { Route as ApiAccountsYoutubeConnectRouteImport } from './routes/api/accounts/youtube/connect'
import { Route as ApiAccountsYoutubeCallbackRouteImport } from './routes/api/accounts/youtube/callback'

const WorkspacesRoute = WorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulerRoute = SchedulerRouteImport.update({
  id: '/scheduler',
  path: '/scheduler',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventsRoute,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => EventsRoute,
} as any)
const ApiYoutubeSyncRoute = ApiYoutubeSyncRouteImport.update({
  id: '/api/youtube/sync',
  path: '/api/youtube/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiYoutubeMetricsRoute = ApiYoutubeMetricsRouteImport.update({
  id: '/api/youtube/metrics',
  path: '/api/youtube/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTeamLoginRoute = ApiTeamLoginRouteImport.update({
  id: '/api/team/login',
  path: '/api/team/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiGenerateRoute = ApiAiGenerateRouteImport.update({
  id: '/api/ai/generate',
  path: '/api/ai/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountsYoutubeConnectRoute =
  ApiAccountsYoutubeConnectRouteImport.update({
    id: '/api/accounts/youtube/connect',
    path: '/api/accounts/youtube/connect',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAccountsYoutubeCallbackRoute =
  ApiAccountsYoutubeCallbackRouteImport.update({
    id: '/api/accounts/youtube/callback',
    path: '/api/accounts/youtube/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/calendar': typeof CalendarRoute
  '/events': typeof EventsRouteWithChildren
  '/scheduler': typeof SchedulerRoute
  '/workspaces': typeof WorkspacesRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/events/': typeof EventsIndexRoute
  '/api/ai/generate': typeof ApiAiGenerateRoute
  '/api/team/login': typeof ApiTeamLoginRoute
  '/api/youtube/metrics': typeof ApiYoutubeMetricsRoute
  '/api/youtube/sync': typeof ApiYoutubeSyncRoute
  '/api/accounts/youtube/callback': typeof ApiAccountsYoutubeCallbackRoute
  '/api/accounts/youtube/connect': typeof ApiAccountsYoutubeConnectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/calendar': typeof CalendarRoute
  '/scheduler': typeof SchedulerRoute
  '/workspaces': typeof WorkspacesRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/events': typeof EventsIndexRoute
  '/api/ai/generate': typeof ApiAiGenerateRoute
  '/api/team/login': typeof ApiTeamLoginRoute
  '/api/youtube/metrics': typeof ApiYoutubeMetricsRoute
  '/api/youtube/sync': typeof ApiYoutubeSyncRoute
  '/api/accounts/youtube/callback': typeof ApiAccountsYoutubeCallbackRoute
  '/api/accounts/youtube/connect': typeof ApiAccountsYoutubeConnectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/calendar': typeof CalendarRoute
  '/events': typeof EventsRouteWithChildren
  '/scheduler': typeof SchedulerRoute
  '/workspaces': typeof WorkspacesRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/events/': typeof EventsIndexRoute
  '/api/ai/generate': typeof ApiAiGenerateRoute
  '/api/team/login': typeof ApiTeamLoginRoute
  '/api/youtube/metrics': typeof ApiYoutubeMetricsRoute
  '/api/youtube/sync': typeof ApiYoutubeSyncRoute
  '/api/accounts/youtube/callback': typeof ApiAccountsYoutubeCallbackRoute
  '/api/accounts/youtube/connect': typeof ApiAccountsYoutubeConnectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/calendar'
    | '/events'
    | '/scheduler'
    | '/workspaces'
    | '/events/$eventId'
    | '/events/'
    | '/api/ai/generate'
    | '/api/team/login'
    | '/api/youtube/metrics'
    | '/api/youtube/sync'
    | '/api/accounts/youtube/callback'
    | '/api/accounts/youtube/connect'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/calendar'
    | '/scheduler'
    | '/workspaces'
    | '/events/$eventId'
    | '/events'
    | '/api/ai/generate'
    | '/api/team/login'
    | '/api/youtube/metrics'
    | '/api/youtube/sync'
    | '/api/accounts/youtube/callback'
    | '/api/accounts/youtube/connect'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/calendar'
    | '/events'
    | '/scheduler'
    | '/workspaces'
    | '/events/$eventId'
    | '/events/'
    | '/api/ai/generate'
    | '/api/team/login'
    | '/api/youtube/metrics'
    | '/api/youtube/sync'
    | '/api/accounts/youtube/callback'
    | '/api/accounts/youtube/connect'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CalendarRoute: typeof CalendarRoute
  EventsRoute: typeof EventsRouteWithChildren
  SchedulerRoute: typeof SchedulerRoute
  WorkspacesRoute: typeof WorkspacesRoute
  ApiAiGenerateRoute: typeof ApiAiGenerateRoute
  ApiTeamLoginRoute: typeof ApiTeamLoginRoute
  ApiYoutubeMetricsRoute: typeof ApiYoutubeMetricsRoute
  ApiYoutubeSyncRoute: typeof ApiYoutubeSyncRoute
  ApiAccountsYoutubeCallbackRoute: typeof ApiAccountsYoutubeCallbackRoute
  ApiAccountsYoutubeConnectRoute: typeof ApiAccountsYoutubeConnectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspaces': {
      id: '/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof WorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheduler': {
      id: '/scheduler'
      path: '/scheduler'
      fullPath: '/scheduler'
      preLoaderRoute: typeof SchedulerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof EventsRoute
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof EventsRoute
    }
    '/api/youtube/sync': {
      id: '/api/youtube/sync'
      path: '/api/youtube/sync'
      fullPath: '/api/youtube/sync'
      preLoaderRoute: typeof ApiYoutubeSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/youtube/metrics': {
      id: '/api/youtube/metrics'
      path: '/api/youtube/metrics'
      fullPath: '/api/youtube/metrics'
      preLoaderRoute: typeof ApiYoutubeMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/team/login': {
      id: '/api/team/login'
      path: '/api/team/login'
      fullPath: '/api/team/login'
      preLoaderRoute: typeof ApiTeamLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/generate': {
      id: '/api/ai/generate'
      path: '/api/ai/generate'
      fullPath: '/api/ai/generate'
      preLoaderRoute: typeof ApiAiGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/accounts/youtube/connect': {
      id: '/api/accounts/youtube/connect'
      path: '/api/accounts/youtube/connect'
      fullPath: '/api/accounts/youtube/connect'
      preLoaderRoute: typeof ApiAccountsYoutubeConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/accounts/youtube/callback': {
      id: '/api/accounts/youtube/callback'
      path: '/api/accounts/youtube/callback'
      fullPath: '/api/accounts/youtube/callback'
      preLoaderRoute: typeof ApiAccountsYoutubeCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EventsRouteChildren {
  EventsEventIdRoute: typeof EventsEventIdRoute
  EventsIndexRoute: typeof EventsIndexRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsEventIdRoute: EventsEventIdRoute,
  EventsIndexRoute: EventsIndexRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  CalendarRoute: CalendarRoute,
  EventsRoute: EventsRouteWithChildren,
  SchedulerRoute: SchedulerRoute,
  WorkspacesRoute: WorkspacesRoute,
  ApiAiGenerateRoute: ApiAiGenerateRoute,
  ApiTeamLoginRoute: ApiTeamLoginRoute,
  ApiYoutubeMetricsRoute: ApiYoutubeMetricsRoute,
  ApiYoutubeSyncRoute: ApiYoutubeSyncRoute,
  ApiAccountsYoutubeCallbackRoute: ApiAccountsYoutubeCallbackRoute,
  ApiAccountsYoutubeConnectRoute: ApiAccountsYoutubeConnectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
