/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SchedulerRouteImport } from './routes/scheduler'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AiStudioRouteImport } from './routes/ai-studio'
import { Route as IndexRouteImport } from './routes/index'

const SchedulerRoute = SchedulerRouteImport.update({
  id: '/scheduler',
  path: '/scheduler',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AiStudioRoute = AiStudioRouteImport.update({
  id: '/ai-studio',
  path: '/ai-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-studio': typeof AiStudioRoute
  '/analytics': typeof AnalyticsRoute
  '/calendar': typeof CalendarRoute
  '/scheduler': typeof SchedulerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-studio': typeof AiStudioRoute
  '/analytics': typeof AnalyticsRoute
  '/calendar': typeof CalendarRoute
  '/scheduler': typeof SchedulerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-studio': typeof AiStudioRoute
  '/analytics': typeof AnalyticsRoute
  '/calendar': typeof CalendarRoute
  '/scheduler': typeof SchedulerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ai-studio' | '/analytics' | '/calendar' | '/scheduler'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ai-studio' | '/analytics' | '/calendar' | '/scheduler'
  id:
    | '__root__'
    | '/'
    | '/ai-studio'
    | '/analytics'
    | '/calendar'
    | '/scheduler'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiStudioRoute: typeof AiStudioRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CalendarRoute: typeof CalendarRoute
  SchedulerRoute: typeof SchedulerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scheduler': {
      id: '/scheduler'
      path: '/scheduler'
      fullPath: '/scheduler'
      preLoaderRoute: typeof SchedulerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-studio': {
      id: '/ai-studio'
      path: '/ai-studio'
      fullPath: '/ai-studio'
      preLoaderRoute: typeof AiStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiStudioRoute: AiStudioRoute,
  AnalyticsRoute: AnalyticsRoute,
  CalendarRoute: CalendarRoute,
  SchedulerRoute: SchedulerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
